-- Drop the existing table if it exists
DROP TABLE IF EXISTS players;

-- Create the new simplified players table
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    rank INTEGER NOT NULL,
    cost NUMERIC(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create an index on rank for faster queries
CREATE INDEX idx_players_rank ON players(rank);

-- Create an index on country for faster queries
CREATE INDEX idx_players_country ON players(country);

-- Enable Row Level Security (optional)
ALTER TABLE players ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow all operations for all users (including anon)
CREATE POLICY "Enable all operations for all users" ON players
FOR ALL USING (true);

-- Alternative: Create specific policies for different operations
-- CREATE POLICY "Enable read access for all" ON players FOR SELECT USING (true);
-- CREATE POLICY "Enable insert access for all" ON players FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Enable update access for all" ON players FOR UPDATE USING (true);
-- CREATE POLICY "Enable delete access for all" ON players FOR DELETE USING (true);
